name: Android
on: 
  push:
    paths:
      - '*.pro'
      - 'src/**'
      - '.github/workflows/android.yml'
  pull_request:
    paths:
      - '*.pro'
      - 'src/**'
      - '.github/workflows/android.yml'  
jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - qt_ver: 5.12.10
            qt_arch: android_x86
            os: ubuntu-20.04
            qt_target: android
          - qt_ver: 5.12.10
            qt_arch: android_armv7
            os: ubuntu-20.04
            qt_target: android            
          - qt_ver: 5.12.10
            qt_arch: android_arm64_v8a
            os: ubuntu-20.04
            qt_target: android            
          - qt_ver: 5.15.2
            # here no qt_arch, use default
            os: ubuntu-20.04
            qt_target: android            
    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        if: ${{ matrix.qt_ver == '5.12.10' }}
        with:
          version: ${{ matrix.qt_ver }}
          target: ${{ matrix.qt_target }}
          arch: ${{ matrix.qt_arch }}  
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        if: ${{ matrix.qt_ver == '5.15.2' }}
        with:
          version: ${{ matrix.qt_ver }}
          target: ${{ matrix.qt_target }}
          # here need not arch
          # arch: ${{ matrix.qt_arch }}            
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: build android
        run: |
          export ANDROID_SDK_ROOT=$ANDROID_HOME
          export ANDROID_NDK_ROOT=$ANDROID_HOME/ndk-bundle
          qmake
          make